### ISSUE TITLE
编译会出错

### ISSUE THREAD

**Issue by zzhignore1** [yigger/jiezhang#3]
有没有生成好的dist文件

**Comment by yigger** [comment]
@zzhignore1 把错误代码贴出来

**Comment by zzhignore1** [comment]
Unable to save binary /home/app/zAccount/jiezhang-master/node_modules/node-sass/vendor/linux-x64-59 : { Error: EACCES: permission denied, mkdir '/home/app/zAccount/jiezhang-master/node_modules/node-sass/vendor'
    at Object.fs.mkdirSync (fs.js:909:18)
    at sync (/home/app/zAccount/jiezhang-master/node_modules/mkdirp/index.js:71:13)
    at Function.sync (/home/app/zAccount/jiezhang-master/node_modules/mkdirp/index.js:77:24)
    at checkAndDownloadBinary (/home/app/zAccount/jiezhang-master/node_modules/node-sass/scripts/install.js:114:11)
    at Object.<anonymous> (/home/app/zAccount/jiezhang-master/node_modules/node-sass/scripts/install.js:157:1)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/home/app/zAccount/jiezhang-master/node_modules/node-sass/vendor' }

**Comment by yigger** [comment]
@zzhignore1 这个是权限问题，你确定一下当前工作目录的当前登录用户是否有权限创建文件夹
