### ISSUE TITLE
创建数据库时报错，bundle exec rake db:create RAILS_ENV=development --trace

### ISSUE THREAD

**Issue by xiangforever2014** [yigger/jiezhang#41]
$ bundle exec rake db:create RAILS_ENV=development --trace
/var/lib/gems/2.7.0/gems/mime-types-3.2.2/lib/mime/types/logger.rb:30: warning: `_1' is reserved for numbered parameter; consider another name
/var/lib/gems/2.7.0/gems/mime-types-3.2.2/lib/mime/types/logger.rb:30: warning: `_2' is reserved for numbered parameter; consider another name
/var/lib/gems/2.7.0/gems/mime-types-3.2.2/lib/mime/types/logger.rb:30: warning: `_3' is reserved for numbered parameter; consider another name
/var/lib/gems/2.7.0/gems/dry-configurable-0.8.2/lib/dry/configurable/settings/argument_parser.rb:41: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/var/lib/gems/2.7.0/gems/dry-configurable-0.8.2/lib/dry/configurable/settings/argument_parser.rb:44: warning: The called method `options' is defined here
/var/lib/gems/2.7.0/gems/dry-types-0.14.0/lib/dry/types/any.rb:5: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/var/lib/gems/2.7.0/gems/dry-types-0.14.0/lib/dry/types/definition.rb:30: warning: The called method `initialize' is defined here
/var/lib/gems/2.7.0/gems/dry-types-0.14.0/lib/dry/types/decorator.rb:13: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/var/lib/gems/2.7.0/gems/dry-types-0.14.0/lib/dry/types/options.rb:8: warning: The called method `initialize' is defined here
/var/lib/gems/2.7.0/gems/dry-types-0.14.0/lib/dry/types/sum.rb:43: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/var/lib/gems/2.7.0/gems/dry-types-0.14.0/lib/dry/types/options.rb:8: warning: The called method `initialize' is defined here
rake aborted!
NoMethodError: undefined method `new_ostruct_member' for #<Config::Options>
/var/lib/gems/2.7.0/gems/config-1.7.1/lib/config/options.rb:175:in `method_missing'
/var/lib/gems/2.7.0/gems/config-1.7.1/lib/config/options.rb:202:in `block in __convert'
/var/lib/gems/2.7.0/gems/config-1.7.1/lib/config/options.rb:200:in `each'
/var/lib/gems/2.7.0/gems/config-1.7.1/lib/config/options.rb:200:in `__convert'
/var/lib/gems/2.7.0/gems/config-1.7.1/lib/config/options.rb:91:in `reload!'
/var/lib/gems/2.7.0/gems/config-1.7.1/lib/config.rb:49:in `load_files'
/var/lib/gems/2.7.0/gems/config-1.7.1/lib/config.rb:57:in `load_and_set_settings'
/var/lib/gems/2.7.0/gems/config-1.7.1/lib/config/integrations/rails/railtie.rb:11:in `preload'
/var/lib/gems/2.7.0/gems/railties-5.1.6.1/lib/rails/railtie.rb:185:in `public_send'
/var/lib/gems/2.7.0/gems/railties-5.1.6.1/lib/rails/railtie.rb:185:in `method_missing'
/var/lib/gems/2.7.0/gems/config-1.7.1/lib/config/integrations/rails/railtie.rb:21:in `block in <class:Railtie>'
/var/lib/gems/2.7.0/gems/activesupport-5.1.6.1/lib/active_support/lazy_load_hooks.rb:67:in `block in execute_hook'
/var/lib/gems/2.7.0/gems/activesupport-5.1.6.1/lib/active_support/lazy_load_hooks.rb:60:in `with_execution_control'
/var/lib/gems/2.7.0/gems/activesupport-5.1.6.1/lib/active_support/lazy_load_hooks.rb:65:in `execute_hook'
/var/lib/gems/2.7.0/gems/activesupport-5.1.6.1/lib/active_support/lazy_load_hooks.rb:50:in `block in run_load_hooks'
/var/lib/gems/2.7.0/gems/activesupport-5.1.6.1/lib/active_support/lazy_load_hooks.rb:49:in `each'
/var/lib/gems/2.7.0/gems/activesupport-5.1.6.1/lib/active_support/lazy_load_hooks.rb:49:in `run_load_hooks'
/var/lib/gems/2.7.0/gems/railties-5.1.6.1/lib/rails/application.rb:91:in `inherited'
/home/ubuntu/jiezhang-back-open/config/application.rb:11:in `<module:JieZhang>'
/home/ubuntu/jiezhang-back-open/config/application.rb:9:in `<top (required)>'
/home/ubuntu/jiezhang-back-open/Rakefile:4:in `require_relative'
/home/ubuntu/jiezhang-back-open/Rakefile:4:in `<top (required)>'
/var/lib/gems/2.7.0/gems/rake-12.3.2/lib/rake/rake_module.rb:29:in `load'
/var/lib/gems/2.7.0/gems/rake-12.3.2/lib/rake/rake_module.rb:29:in `load_rakefile'
/var/lib/gems/2.7.0/gems/rake-12.3.2/lib/rake/application.rb:703:in `raw_load_rakefile'
/var/lib/gems/2.7.0/gems/rake-12.3.2/lib/rake/application.rb:104:in `block in load_rakefile'
/var/lib/gems/2.7.0/gems/rake-12.3.2/lib/rake/application.rb:186:in `standard_exception_handling'
/var/lib/gems/2.7.0/gems/rake-12.3.2/lib/rake/application.rb:103:in `load_rakefile'
/var/lib/gems/2.7.0/gems/rake-12.3.2/lib/rake/application.rb:82:in `block in run'
/var/lib/gems/2.7.0/gems/rake-12.3.2/lib/rake/application.rb:186:in `standard_exception_handling'
/var/lib/gems/2.7.0/gems/rake-12.3.2/lib/rake/application.rb:80:in `run'
/var/lib/gems/2.7.0/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
/usr/local/bin/rake:23:in `load'
/usr/local/bin/rake:23:in `<main>'

错误信息如上，请各位大佬看看是什么原因，谢谢！

**Comment by oemsys** [comment]
有没有成品DOCKER 呀，不会呀~！~！~！
